### ISSUE TITLE
UI control for "interaction speedup"

### ISSUE THREAD

**Issue by hubbardp** [JaneliaSciComp/neuronbridge-vol-viewer#1]
The UI should have a control to specify the `interactionSpeedup` prop for `Vol3DViewer`, as added here:

https://github.com/JaneliaSciComp/web-vol-viewer/commit/5fec30823cd5ec604da79589736a261ea7afe56d

A value of 1 gives the normal behavior.  A value above 1 reduces the resolution when the mouse is down, improving interactive performance for big volumes or low capability hosts.  A value of 20 is probably a reasonable maximum.

**Comment by neomorphic** [comment]
This and a few of the other controls seem like "Advanced" settings that might want to be hidden by default. I think there should probably be a dropdown menu that has this control and possibly the sample spacing control hidden away until someone needs them.

**Comment by hubbardp** [comment]
I definitely agree some controls should be in an "advanced" panel.  But this control could be very important, if it is the difference between a user being able to interact comfortably and giving up using the system because it feels too slow.

**Comment by neomorphic** [comment]
This control has been added in 7eee10ff485535ef361241a1e7d18caf5cc8f3a7
