### ISSUE TITLE
NeuronBridge "Download 3D FIles" needs rewording

### ISSUE THREAD

**Issue by hubbardp** [JaneliaSciComp/neuronbridge-vol-viewer#2]
In NeuronBridge, the way to get to a live `neuronbridge-vol-viewer` session is by pressing the "Download 3D Files" tab in the search results page.  I think the wording for that tab should be chanced, since users will not think of `neuronbridge-vol-viewer` as "downloading files".

How about "View or Download 3D"?

**Comment by neomorphic** [comment]
I plan on moving the button elsewhere, that was a temporary location for testing

**Comment by hubbardp** [comment]
Great!
